-- Rode isso no SQL Editor do seu projeto Supabase (Supabase > SQL Editor > New query)

create table if not exists entradas (
  id bigint generated by default as identity primary key,
  name text not null,
  value numeric not null,
  date date not null,
  status text not null default 'recebido',
  created_at timestamptz not null default now()
);

create table if not exists gastos_fixos (
  id bigint generated by default as identity primary key,
  name text not null,
  due_day int not null,
  category text not null default 'outros',
  payment_method text not null default 'pix',
  value numeric not null,
  paid boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists gastos_variaveis (
  id bigint generated by default as identity primary key,
  name text not null,
  date date not null,
  category text not null default 'outros',
  payment_method text not null default 'pix',
  value numeric not null,
  paid boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists parcelamentos (
  id bigint generated by default as identity primary key,
  name text not null,
  total_parcelas int not null,
  parcela_atual int not null default 1,
  category text not null default 'outros',
  payment_method text not null default 'pix',
  valor_parcela numeric not null,
  paid boolean not null default false,
  created_at timestamptz not null default now()
);

-- Habilita RLS (Row Level Security) — obrigatório no Supabase
alter table entradas enable row level security;
alter table gastos_fixos enable row level security;
alter table gastos_variaveis enable row level security;
alter table parcelamentos enable row level security;

-- Política permissiva: como o app ainda não tem login, liberamos leitura/escrita
-- pra quem tiver a chave publishable. Bom o suficiente pra uso pessoal agora;
-- quando adicionar login, troque isso para restringir por usuário.
create policy "Allow all - entradas" on entradas for all using (true) with check (true);
create policy "Allow all - gastos_fixos" on gastos_fixos for all using (true) with check (true);
create policy "Allow all - gastos_variaveis" on gastos_variaveis for all using (true) with check (true);
create policy "Allow all - parcelamentos" on parcelamentos for all using (true) with check (true);
